### ISSUE TITLE
List of test device ids

### ISSUE THREAD

**Issue by lcuis** [nooralibutt/easy-ads#32]
Is there a way to list the test device ids for each ad network?

**Comment by nooralibutt** [comment]
Not every ad network provide support for test device ids and why do u need to list them and to answer your question. No we can't list the test device ids bcz these test device ids are provided by you so why library should provide that support

**Comment by lcuis** [comment]
I am asking here, on your promising plugin because other plugins support this at least for AdMob. If there is a way to list the device ids without going through the plugin, I am more than happy to try. Listing test device ids is important to me because I need the ability to test without risking getting banned. Banning, at least on AdMob, is pretty irreversible and global for a company - thus, extremely damaging.

**Comment by nooralibutt** [comment]
Oh that device id will be listed automatically in the case of admob and you can mention it while initializing plugin

**Comment by lcuis** [comment]
Indeed, there is a `testDeviceIds` list for AdMob initial configuration. Thanks for that, closing.
