### ISSUE TITLE
How can i stop AppOpen Ads while app is running

### ISSUE THREAD

**Issue by chetan532** [nooralibutt/easy-ads#56]
how i can stop AppOpen ads on button click and not show from running on background to foreground @nooralibutt @rmahmadkhan @pikkenix @mhanzla80

**Comment by nooralibutt** [comment]
As I understand you do not want to show app open ads on app state change, this is currently not supported right now but will implement it for you in next release InShaaAllah

**Comment by nooralibutt** [comment]
its implemented in latest PR
