### ISSUE TITLE
onAdDismissed not called in unity in case of rewarded ads

### ISSUE THREAD

**Issue by niraj-prajapati** [nooralibutt/easy-ads#57]
here in case of rewarded ads, else bloc will never be called

https://github.com/nooralibutt/easy-ads/blob/7f2b091f962587d97c219d68a14568b266539086/lib/src/easy_unity/easy_unity_ad.dart#L76-L83

may be it should be like this

```
  void onCompleteUnityAd(String s) {
    _isAdLoaded = false;
    if (adUnitType == AdUnitType.rewarded) {
      onEarnedReward?.call(adNetwork, adUnitType, null, null);
    }
    onAdDismissed?.call(adNetwork, adUnitType, null);
  }
```

**Comment by nooralibutt** [comment]
Will check this and let u know

**Comment by nooralibutt** [comment]
@niraj-prajapati in case if ad is not rewarded one, for example, if ad is video ad and its completed, then onEarnedReward will not be called, instead onAdDissmissed will be called
