### ISSUE TITLE
Error after changing Ads id

### ISSUE THREAD

**Issue by viralvaghela** [nooralibutt/easy-ads#60]
I have changed the Ads id for fb and then getting this error```I/flutter (23776): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23776): │ #0   EasyLogger._onAdFailedToLoad (package:easy_ads_flutter/src/utils/easy_logger.dart:36:13)
easy_logger.dart:36
I/flutter (23776): │ #1   EasyLogger._onAdEvent (package:easy_ads_flutter/src/utils/easy_logger.dart:76:9)
easy_logger.dart:76
I/flutter (23776): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23776): │ ⛔ interstitial ads for facebook could not be loaded.
I/flutter (23776): │ ⛔ ERROR: Error occurred while loading 1001 No fill ad
I/flutter (23776): └───```

**Comment by nooralibutt** [comment]
Error clearly says there is no fill. If there is no fill from network you can't do anything

**Comment by viralvaghela** [comment]
what is fill from? i have no idea about it

**Comment by nooralibutt** [comment]
Research on it

**Comment by nooralibutt** [comment]
closing this issue, as it is not an issue.
