### ISSUE TITLE
How to remove applovin SDK, JUST Keep Google Admob?

### ISSUE THREAD

**Issue by wangshimeng** [nooralibutt/easy-ads#61]
Hello, we have received email by google, the email shows:

_Your app is not compliant with Google Play Policies_ and
_We found an issue in the following area(s):
SPLIT_BUNDLE 12: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.applovin:applovin-sdk_

We don't want to collect any user data. So, how do I only keep google admob sdk?

Thanks

**Comment by nooralibutt** [comment]
I am really sorry about this @wangshimeng but we do not have a way to exclude applovin as of now, but for now you can mention that you are collecting Device ID because google mobile ads does collect device id for advertising purposes.
