### ISSUE TITLE
Facebook Interstitial Ads Loading Failed with the following error

### ISSUE THREAD

**Issue by dhameliyamilan** [nooralibutt/easy-ads#67]
I/flutter ( 3680): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3680): │ #0   EasyLogger.logInfo (package:easy_ads_flutter/src/utils/easy_logger.dart:19:43)
I/flutter ( 3680): │ #1   EasyAds.showAd (package:easy_ads_flutter/src/easy_ads.dart:394:17)
I/flutter ( 3680): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3680): │ 💡 AdNetwork.facebook AdUnitType.interstitial was not loaded, so called loading
I/flutter ( 3680): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): Failed to handle method call
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at com.dsi.facebook_audience_network.FacebookInterstitialAdPlugin.loadAd(FacebookInterstitialAdPlugin.java:55)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at com.dsi.facebook_audience_network.FacebookInterstitialAdPlugin.onMethodCall(FacebookInterstitialAdPlugin.java:44)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MethodChannel#fb.audience.network.io/interstitialAd( 3680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
E/MethodChannel#fb.audience.network.io/rewardedAd( 3680): Failed to handle method call

**Comment by nooralibutt** [comment]
@dhameliyamilan did you check this issue on original facebook plugin, cz as I see from logs, this issue is not due to our plugin.
