### ISSUE TITLE
Doesn't work Android

### ISSUE THREAD

**Issue by cihanst** [nooralibutt/easy-ads#71]
this works iOS but not work android. when I remove this, android good works

**Comment by nooralibutt** [comment]
It's in all of our apps and it works on android and iOS, can you explain your issue here with bit more detail?

**Comment by cihanst** [comment]
I am so sory. After I upgrade flutter, this happened. It is not problem for easy-ads

**Comment by turbobuilt** [comment]
> this works iOS but not work android. when I remove this, android good works

When I install, my android crashes.  I will try to upgrade flutter
