### ISSUE TITLE
SKAdNetwork support for Audience Network

### ISSUE THREAD

**Issue by makinghappen** [nooralibutt/easy-ads#82]
Does easy-ads support SKAdNetwork for Audience Network?

https://developers.facebook.com/docs/setting-up/platform-setup/ios/SKAdNetwork/

**Comment by cc-hanzla** [comment]
@makinghappen yes it supports SKAdNetwork for Audience Network.

you can check [readme](https://github.com/nooralibutt/easy-ads#ios) for this.
