### ISSUE TITLE
Add support for multiple ad units within a category for direct sale ads

### ISSUE THREAD

**Issue by caseycrogers** [nooralibutt/easy-ads#87]
Firstly, I love this package! You're my hero. It's saving me from so many wasted hours and headaches.

I have typical AdMob interstitial ads and a direct sale AdMob interstitial ad. The direct sale uses a different ad unit, but also has a very low fill rate as it is rate limited to one impression every 12 hours. As such, I'd like the following behavior:
1. Ability to set a list of ad units for any given service and/or format
2. Waterfall behavior where if the first unit fails to load, the next ad unit is attempted, and so on

**Comment by nooralibutt** [comment]
Thank you Casey,We never felt the use of direct sale interstitial ad. But you’re welcome to update the package and create Pull request. We will take a lookOn Thu, 14 Mar 2024 at 4:26 PM Casey Rogers ***@***.***> wrote:
Firstly, I love this package! You're my hero. It's saving me from so many wasted hours and headaches.
I have typical AdMob interstitial ads and a direct sale AdMob interstitial ad. The direct sale uses a different ad unit, but also has a very low fill rate as it is rate limited to one impression every 12 hours. As such, I'd like the following behavior:
Ability to set a list of ad units for any given service and/or formatWaterfall behavior where if the first unit fails to load, the next ad unit is attempted, and so on
