### ISSUE TITLE
The getter 'targetingData' isn't defined for the type 'AppLovinMAX'.

### ISSUE THREAD

**Issue by wantroba** [nooralibutt/easy-ads#97]
Until yesterday I was able to generate the .ipa for my app but now I'm getting this error:

Error (Xcode): ../.pub-cache/hosted/pub.dev/easy_ads_flutter-2.4.4/lib/src/easy_ads.dart:241:17: Error: Member not found: 'targetingData'.

My Info.Plist contains this key

`<key>AppLovinSdkKey</key><string>{my key}</string>`

I'm not using app loving ads:

```
@override
AppAdIds? get appLovinAdIds => null;
```

**Comment by wantroba** [comment]
I think it's related to this:
![image](https://github.com/user-attachments/assets/cd103bd1-9a70-46eb-90ce-9c0c7b4b61ef)

**Comment by nooralibutt** [comment]
@wantroba this is fixed in new release

**Comment by wantroba** [comment]
> @wantroba this is fixed in new release

Thank you very much for resolving it so quickly @nooralibutt . Everything is working perfectly now!
